name: deploy-site
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch pelican-plugins
        run: |
          git submodule update --init --recursive
          git fetch --recurse-submodules
          git pull --recurse-submodules

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Pelican Build
        run: |
          pip install -r requirements.txt
          pelican-themes --install themes/attila
          make html

      - name: Deploy Build
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
