name: deploy-site
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch pelican-plugins
        run: |
          git submodule update --init --recursive
          git fetch --recurse-submodules
          git pull --recurse-submodules

      - name: GitHub Pages Pelican Build Action
        uses: nelsonjchen/gh-pages-pelican-action@0.1.5
        with:
          GH_PAGES_BRANCH: deploy
          PELICAN_CONFIG_FILE: pelicanconf.py